#!/usr/bin/env bash

system_type="$(uname -s)"

if [ "$system_type" = "Darwin" ]; then
  # Install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

if [ "$system_type" = "Linux" ]; then
  # Install Zsh if it's missing
  if ! command -v zsh >/dev/null 2>&1; then
    sudo apt install zsh
  fi

  # Install Starship prompt if it's missing
  if ! command -v starship >/dev/null 2>&1; then
    wget -q -O - https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz | tar xz
    sudo mv starship /usr/local/bin/
  fi

  # Install Zplug if it's missing
  if ! command -v zplug >/dev/null 2>&1; then
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  fi
fi

# Set default shell to Zsh
chsh -s "$(command -v zsh)"
