#!/usr/bin/env bash

# Loop through directories
for dir in *; do
    if [[ -d "${dir}/.git" ]]; then
        echo ${dir}
        # Run the garbage collector to optimize the repository
        git -C ${dir} gc --auto
    fi
done
