#!/usr/bin/env bash

# Pipe current user's public key to clipboard
if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
    xsel -b < "$HOME/.ssh/id_ed25519.pub"
elif [[ -f "$HOME/.ssh/id_rsa.pub" ]]; then
    xsel -b < "$HOME/.ssh/id_rsa.pub"
else
    echo '=> No public keys available.'
    exit
fi

echo '=> Public key copied to clipboard.'
