[aws]
disabled = true

[battery]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[git_branch]
symbol = " "

[golang]
disabled = true

[hg_branch]
symbol = " "

[java]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[memory_usage]
disabled = true

[package]
symbol = " "

[php]
symbol = " "

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[singularity]
disabled = true

[terraform]
disabled = true

[time]
disabled = true
