[aws]
disabled = true

[battery]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = true

[memory_usage]
disabled = true

[package]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[terraform]
disabled = true

[time]
disabled = true
