# Include local/bin directory
if [ -d "/usr/local/bin" ] ; then
    PATH="/usr/local/bin:$PATH"
fi

# Include custom dotfiles bin directory
if [ -d "$HOME/.dotfiles/bin" ] ; then
    PATH="$HOME/.dotfiles/bin:$PATH"
fi

# Include Composer bin directory
if [ -d "$HOME/.composer/vendor/bin" ]
then
    PATH="$HOME/.composer/vendor/bin:$PATH"
elif [ -d "$HOME/.config/composer/bin" ]
then
    PATH="$HOME/.config/composer/bin:$PATH"
fi

# Include aliases
source $HOME/.dotfiles/zsh/aliases.sh
