source ~/.zplug/init.zsh

# Aliases
alias artisan="php artisan"

# compinit
autoload -Uz compinit
compinit

# zplug
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Theme
zplug "themes/robbyrussell", from:oh-my-zsh

# Plugins
zplug "plugins/git", from:oh-my-zsh
zplug "bobthecow/git-flow-completion"

# Load Plugins
zplug load

