source ~/.zplug/init.zsh

# compinit
autoload -Uz compinit
compinit

# zplug
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# Theme
zplug "themes/robbyrussell", from:oh-my-zsh

# Plugins
zplug "plugins/git", from:oh-my-zsh
zplug "bobthecow/git-flow-completion"
zplug "supercrabtree/k"

# Evals
eval "$(phpenv init -)"

# Load Plugins
zplug load
