source $HOME/.zplug/init.zsh

# compinit
autoload -Uz compinit
compinit

# zplug
zplug "zplug/zplug", hook-build:'zplug --self-manage'

# Theme
zplug "dracula/zsh", as:theme

# Plugins
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/nvm", from:oh-my-zsh
zplug "bobthecow/git-flow-completion"
zplug "sptndc/phpenv.plugin.zsh"

# Install any missing plugins
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Load Plugins
zplug load

# Load Aliases
source $HOME/.dotfiles/zsh/aliases.sh
