#!/usr/bin/env bash

echo "Updating the yadm repo origin URL to SSH"
yadm remote set-url origin "git@github.com:pxgamer/dotfiles.git"

system_type="$(uname -s)"

if [ "$system_type" = "Darwin" ]; then
  # Install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi
fi

if [ "$system_type" = "Linux" ]; then
  # Install Zsh if it's missing
  if ! command -v zsh >/dev/null 2>&1; then
    sudo apt install zsh
  fi

  # Install Zplug if it's missing
  if ! command -v zplug >/dev/null 2>&1; then
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  fi
fi

# Set default shell to Zsh
chsh -s $(which zsh)
